### ISSUE TITLE
npm install --global @ui-js/grok

### ISSUE THREAD

**Issue by physedo** [ui-js/grok#1]
I get this error 

`(base)` ai@physedo:~$ npm install -g @ui-js/grok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/@ui-js/grok/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/ai/.nvm/versions/node/v12.18.1/lib/node_modules/@ui-js/grok/bin/grok-cli
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/ai/.nvm/versions/node/v12.18.1/lib/node_modules/@ui-js/grok/bin/grok-cli'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ai/.npm/_logs/2020-06-24T09_58_36_074Z-debug.log`

**Comment by arnog** [comment]
OK, should be fixed now.
